export  const  SET_SELECTED_PRODUCT  =  "SELECT_PRODUCT" ;
export  const  ADD_CART  =  "ADD_CART" ;
export  const  REMOVE_CART  =  "REMOVE_CART" ;
export const DECREMENT_QUANTITY="DECREMENT_QUANTITY"

export const UPDATE_CART_ITEM = 'cart/UPDATE_CART_ITEM';
export const UPDATE_CART_ITEM_QUANTITY = 'cart/UPDATE_CART_ITEM_QUANTITY';
export const CLEAR_CART = 'cart/CLEAR_CART';
export const INCREMENT_PRODUCT_QUANTITY="INCREMENT_PRODUCT_QUANTITY"
export const DECREMENT_PRODUCT_QUANTITY="DECREMENT_PRODUCT_QUANTITY"